name: Build & Push Docker Image for Pancharm app

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Maven clean & build
        run: mvn -B clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set image tag by branch
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "IMAGE_TAG=prod-latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=staging-latest" >> $GITHUB_ENV
          fi

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: phantuanviet0706/pancharm:latest

#      - name: Deploy to EC2
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ubuntu
#          key: ${{ secrets.EC2_SSH_Key }}
#          script: |
#            cd ~/pancharm
#            ./redeploy.sh